name: Java CI with Maven and TestRigor

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger TestRigor Tests
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            -H 'auth-token: ee87baf9-a11b-43a5-8269-e117e5080d01' \
            --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
            https://api.testrigor.com/api/v1/apps/ma2sa5KtrWidgroow/retest

      - name: Poll TestRigor Status
        run: |
          sleep 10
          while true; do
            echo " "
            echo "==================================="
            echo " Checking TestRigor run status"
            echo "==================================="
            response=$(curl -i -s -X GET 'https://api.testrigor.com/api/v1/apps/ma2sa5KtrWidgroow/status' \
              -H 'auth-token: ee87baf9-a11b-43a5-8269-e117e5080d01' \
              -H 'Accept: application/json')
            code=$(echo "$response" | grep HTTP | awk '{print $2}')
            body=$(echo "$response" | sed -n '/{/,/}/p')
            echo "Status code: $code"
            echo "Response: $body"
            case $code in
              4*|5*)
                echo "❌ Error calling API"
                exit 1
                ;;
              200)
                echo "✅ Test finished successfully"
                exit 0
                ;;
              227|228)
                echo "⏳ Test is still running..."
                ;;
              230)
                echo "❌ Test finished but failed"
                exit 1
                ;;
              *)
                echo "❓ Unknown status"
                exit 1
                ;;
            esac
            sleep 10
          done

  
